steps:
  - name: google/cloud-sdk:slim
    id: 'initialize'
    script: |
      #!/usr/bin/env bash
      cd /workspace/ && ./scripts/fetch_build_key.sh && ./scripts/fetch_and_increment_build_number.sh && ./scripts/update_build_numbers.sh

  - name: 'maven:3-openjdk-17'
    waitFor: ['initialize']
    id: 'keycloak-java-build'
    args: [ '/workspace/mvnw', '-DskipTests', 'clean', 'install', '-f', '/workspace/pom.xml', '-Pdistribution' ]

  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    waitFor: ['keycloak-java-build']
    id: 'keycloak-docker-build'
    args: [ '-c', 'docker build -t us-docker.pkg.dev/non-production-381217/wellstand-docker/keycloak:24.0.$(cat /workspace/keycloak-build-number.txt)' /workspace' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    id: 'upload-keycloak-container'
    waitFor: ['keycloak-docker-build']
    args: ['-c', 'docker push us-docker.pkg.dev/non-production-381217/wellstand-docker/keycloak:24.0.$(cat /workspace/keycloak-build-number.txt)']

options:
  pool:
    name: 'projects/non-production-381217/locations/us-central1/workerPools/build-pool'